version: '3.8'

services:
  app:
    build: .
    container_name: github-actions-dashboard
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health", "--method=GET", "--header=Accept: application/json", "--no-check-certificate"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
